experiment:
  name: mitstates/log

dataset:
  data_dir: mit-states
  dataset: mitstates
  splitname: compositional-split-natural

model_params:
  model: VIT-base
  dropout: true
  norm: true
  nlayers: 3
  fc_emb: 1024,2048
  emb_dim: 768
  emb_init: glove
  image_extractor: vit-base
  use_calibration: false
  use_os_osp: false
  train_only: true
  open_world: false

training:
  max_epochs: 200
  batch_size: 128
  test_batch_size: 64
  start_syn: 60
  test_set: val
  eval_val_every: 1
  lr: 2.0e-05
  wd: 5.0e-05
  lrg: 5.0e-6
  margin: 0.5
  attr_loss_w: 1.0
  obj_loss_w: 1.0
  attack_weight: 0.1
  cosine_scale_p: 20
  cosine_scale_so: 140
  calibration_weights: 0.2
  norm_family: imagenet
  save_every: 1000
  topk: 1
  workers: 8
  finetune_backbone: false
  use_precomputed_features: true
  freeze_features: false
  load_save_embeddings: true

validating:
  attr_score_weight: 1.0
  obj_score_weight: 1.0

