experiment:
  name: utzappos/log
dataset:
  data_dir: ut-zap50k
  dataset: utzappos
  splitname: compositional-split-natural

model_params:
  model: VIT-base
  image_extractor: vit-base
  emb_init: glove
  emb_dim: 300
  dropout: true
  norm: true
  nlayers: 3
  fc_emb: 1024,2048
  use_calibration : true
  train_only: true
  open_world: true
training:
  batch_size: 128
  test_batch_size: 64
  max_epochs: 200
  start_syn: 50
  cosine_scale_p: 20
  cosine_scale_so: 50
  calibration_weights: 0.05
  lr: 2.0e-05
  wd: 5.0e-05
  lrg: 5.0e-6
  eval_val_every: 1
  margin: 0.5
  attr_loss_w: 1.0
  obj_loss_w: 1.0
  norm_family: imagenet
  save_every: 10000
  test_set: val
  topk: 1
  workers: 8
  finetune_backbone: false
  use_precomputed_features: true
  freeze_features: false
  load_save_embeddings: true

validating:
  attr_score_weight: 1.0
  obj_score_weight: 1.0
